name: Build-And-Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

    - name: Build Image
      run: |
        docker build -t onlinebookstore .

    - name: Tag Image
      run: |
        docker tag onlinebookstore:latest ${{ secrets.ECR_URL }}:latest

    - name: Push Image
      run: |
        docker push ${{ secrets.ECR_URL }}:latest

    - name: Force ECS Deploy
      run: |
        aws ecs update-service \
          --cluster onlinebookstore-cluster \
          --service onlinebookstore-service \
          --force-new-deployment
